name: Build & Release

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Test
        run: |
          go test -v -json -coverprofile coverage.out ./... | tee test-results.jsonl

      - name: Run Qase Reporter
        run: |
          go run . \
            --api-token ${{ secrets.QASE_API_TOKEN }} \
            --project ${{ secrets.QASE_PROJECT }} \
            --run-title "Pipeline run $(date +%Y%m%d%H%M%S)" \
            test-results.jsonl
      
      - name: Debug tag
        if: github.event_name != 'pull_request' && github.ref == 'refs/tags/v*'
        run: |
          echo "Tag: ${{ github.ref_name }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          # print git tag
          git tag

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        # Run on tag v*
        if: github.event_name != 'pull_request' && github.ref == 'refs/tags/v*'
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}